"Cart.MD5" "@@MD5@@"
"Cart.Manufacturer" "Bruce-Robert Pocock"
"Cart.ModelNo" "Metr0.NoSave.@@TV@@"
"Cart.Name" "Meteoroid No-Save Demo"
"Cart.Rarity" "Homebrew"
"Cart.Type" "F4"
"Controller.Left" "GENESIS"
"Controller.Right" "JOYSTICK"
"Display.Format" "@@TV@@"
"Display.Phosphor" "YES"
