"Cart.MD5" "@@MD5@@"
"Cart.Manufacturer" "Bruce-Robert Pocock"
"Cart.ModelNo" "Metr0.@@TV@@"
"Cart.Name" "Meteoroid"
"Cart.Rarity" "Homebrew"
"Cart.Type" "EF"
"Controller.Left" "GENESIS"
"Controller.Right" "ATARIVOX"
"Display.Format" "@@TV@@"
"Display.Phosphor" "YES"
