"Cart.MD5" "@@MD5@@"
"Cart.Manufacturer" "Bruce-Robert Pocock"
"Cart.ModelNo" "Metr0.Demo.@@TV@@"
"Cart.Name" "Meteoroid Demo"
"Cart.Rarity" "Homebrew"
"Cart.Type" "F4SC"
"Controller.Left" "GENESIS"
"Controller.Right" "ATARIVOX"
"Display.Format" "@@TV@@"
"Display.Phosphor" "YES"
